using Mosaic.SourceGenerator.Analysis;

namespace Mosaic.SourceGenerator.Emit;

internal static class EngineEmitter
{
    public static string Emit(HandlerCatalog catalog)
    {
        var cb = new CodeBuilder();

        cb.AppendLine("// <auto-generated />");
        cb.AppendLine("// Generated by Mosaic.SourceGenerator. Do not edit.");
        cb.AppendLine("#nullable enable");
        cb.AppendLine();
        cb.AppendLine("using System;");
        cb.AppendLine("using System.Runtime.CompilerServices;");
        cb.AppendLine("using System.Text.Json;");
        cb.AppendLine("using System.Threading;");
        cb.AppendLine("using System.Threading.Tasks;");
        cb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        cb.AppendLine("using Mosaic;");
        cb.AppendLine("using Mosaic.Runtime;");
        cb.AppendLine();
        cb.AppendLine($"namespace {catalog.GeneratedNamespace};");
        cb.AppendLine();

        cb.AppendLine("/// <summary>Source-generated implementation of <see cref=\"global::Mosaic.ICompositionEngine\"/>.</summary>");
        cb.AppendLine("internal sealed class GeneratedCompositionEngine : global::Mosaic.ICompositionEngine, global::Mosaic.IInboundEventDispatcher");
        cb.OpenBrace();

        cb.AppendLine("private readonly global::System.IServiceProvider _services;");
        cb.AppendLine("private readonly global::Mosaic.IEventTransport _transport;");
        cb.AppendLine("private readonly global::Mosaic.IMosaicSerializerRegistry _serializerRegistry;");
        cb.AppendLine("private readonly global::Mosaic.IMessageAuditStore _auditStore;");
        cb.AppendLine();
        cb.AppendLine("public GeneratedCompositionEngine(global::System.IServiceProvider services, global::Mosaic.IEventTransport transport, global::Mosaic.IMosaicSerializerRegistry serializerRegistry, global::Mosaic.IMessageAuditStore auditStore)");
        cb.OpenBrace();
        cb.AppendLine("_services = services;");
        cb.AppendLine("_transport = transport;");
        cb.AppendLine("_serializerRegistry = serializerRegistry;");
        cb.AppendLine("_auditStore = auditStore;");
        cb.CloseBrace();
        cb.AppendLine();

        EmitSendDispatch(cb, catalog);
        cb.AppendLine();
        EmitComposeAllocatingDispatch(cb, catalog);
        cb.AppendLine();
        EmitComposeExistingDispatch(cb, catalog);
        cb.AppendLine();
        EmitPublishDispatch(cb, catalog);
        cb.AppendLine();
        EmitInboundDispatch(cb, catalog);
        cb.AppendLine();

        foreach (var request in catalog.Requests)
        {
            EmitSendInner(cb, request, catalog);
            cb.AppendLine();
        }

        foreach (var composable in catalog.Composables)
        {
            EmitComposeInner(cb, composable, catalog);
            cb.AppendLine();
        }

        foreach (var ev in catalog.Events)
        {
            EmitPublishInner(cb, ev, catalog);
            cb.AppendLine();
        }

        cb.CloseBrace();

        return cb.ToString();
    }

    // ─── Public dispatch methods (the switches) ─────────────────────────────────────────────────

    private static void EmitSendDispatch(CodeBuilder cb, HandlerCatalog catalog)
    {
        cb.AppendLine("public global::System.Threading.Tasks.ValueTask<TResponse> Send<TResponse>(global::Mosaic.IRequest<TResponse> request, global::System.Threading.CancellationToken cancellationToken = default)");
        cb.OpenBrace();
        if (catalog.Requests.Count > 0)
        {
            cb.AppendLine("switch (request)");
            cb.OpenBrace();
            foreach (var r in catalog.Requests)
            {
                cb.AppendLine($"case {r.RequestFullName} __r:");
                cb.AppendLine("    {");
                cb.AppendLine($"        var __task = Send_{r.MethodSafeName}(__r, cancellationToken);");
                cb.AppendLine($"        return global::System.Runtime.CompilerServices.Unsafe.As<global::System.Threading.Tasks.ValueTask<{r.ResponseFullName}>, global::System.Threading.Tasks.ValueTask<TResponse>>(ref __task);");
                cb.AppendLine("    }");
            }
            cb.CloseBrace();
        }
        cb.AppendLine("throw new global::Mosaic.SendNoHandlerException(request.GetType());");
        cb.CloseBrace();
    }

    private static void EmitComposeAllocatingDispatch(CodeBuilder cb, HandlerCatalog catalog)
    {
        cb.AppendLine("public global::System.Threading.Tasks.ValueTask<TViewModel> Compose<TViewModel>(global::Mosaic.IComposable<TViewModel> request, global::System.Threading.CancellationToken cancellationToken = default)");
        cb.AppendLine("    where TViewModel : new()");
        cb.OpenBrace();
        if (catalog.Composables.Count > 0)
        {
            cb.AppendLine("switch (request)");
            cb.OpenBrace();
            foreach (var c in catalog.Composables)
            {
                cb.AppendLine($"case {c.RequestFullName} __r:");
                cb.AppendLine("    {");
                cb.AppendLine($"        var __task = Compose_{c.MethodSafeName}(__r, new {c.ViewModelFullName}(), cancellationToken);");
                cb.AppendLine($"        return global::System.Runtime.CompilerServices.Unsafe.As<global::System.Threading.Tasks.ValueTask<{c.ViewModelFullName}>, global::System.Threading.Tasks.ValueTask<TViewModel>>(ref __task);");
                cb.AppendLine("    }");
            }
            cb.CloseBrace();
        }
        cb.AppendLine("throw new global::Mosaic.ComposeNoHandlerException(request.GetType(), typeof(TViewModel));");
        cb.CloseBrace();
    }

    private static void EmitComposeExistingDispatch(CodeBuilder cb, HandlerCatalog catalog)
    {
        cb.AppendLine("public global::System.Threading.Tasks.ValueTask Compose<TViewModel>(global::Mosaic.IComposable<TViewModel> request, TViewModel existing, global::System.Threading.CancellationToken cancellationToken = default)");
        cb.OpenBrace();
        if (catalog.Composables.Count > 0)
        {
            cb.AppendLine("switch (request)");
            cb.OpenBrace();
            foreach (var c in catalog.Composables)
            {
                cb.AppendLine($"case {c.RequestFullName} __r:");
                cb.AppendLine($"    return new global::System.Threading.Tasks.ValueTask(Compose_{c.MethodSafeName}(__r, ({c.ViewModelFullName})(object)existing!, cancellationToken).AsTask());");
            }
            cb.CloseBrace();
        }
        cb.AppendLine("throw new global::Mosaic.ComposeNoHandlerException(request.GetType(), typeof(TViewModel));");
        cb.CloseBrace();
    }

    private static void EmitPublishDispatch(CodeBuilder cb, HandlerCatalog catalog)
    {
        cb.AppendLine("public global::System.Threading.Tasks.ValueTask Publish<TEvent>(TEvent notification, global::System.Threading.CancellationToken cancellationToken = default, global::Mosaic.MessageHeaders? messageHeaders = null)");
        cb.AppendLine("    where TEvent : global::Mosaic.IEvent");
        cb.OpenBrace();
        if (catalog.Events.Count > 0)
        {
            cb.AppendLine("switch (notification)");
            cb.OpenBrace();
            foreach (var e in catalog.Events)
            {
                cb.AppendLine($"case {e.EventFullName} __e:");
                cb.AppendLine($"    return Publish_{e.MethodSafeName}(__e, cancellationToken, fromTransport: false, messageHeaders: messageHeaders);");
            }
            cb.CloseBrace();
        }
        cb.AppendLine("// No handlers registered for this event type — silent no-op.");
        cb.AppendLine("return default;");
        cb.CloseBrace();
    }

    private static void EmitInboundDispatch(CodeBuilder cb, HandlerCatalog catalog)
    {
        cb.AppendLine("public async global::System.Threading.Tasks.Task DispatchInboundAsync(string typeFullName, global::Mosaic.MessageHeaders headers, global::System.Buffers.ReadOnlySequence<byte> payload, global::System.Threading.CancellationToken cancellationToken = default)");
        cb.OpenBrace();
        if (catalog.Events.Count > 0)
        {
            cb.AppendLine("switch (typeFullName)");
            cb.OpenBrace();
            foreach (var e in catalog.Events)
            {
                var stripped = Strip(e.EventFullName);
                cb.AppendLine($"case \"{stripped}\":");
                cb.AppendLine("    {");
                cb.AppendLine($"        var __ser = _serializerRegistry.GetSerializer<{e.EventFullName}>();");
                cb.AppendLine($"        var __evt = __ser.Deserialize(payload)");
                cb.AppendLine($"            ?? throw new global::System.InvalidOperationException(\"Mosaic: inbound payload for {stripped} deserialised to null.\");");
                cb.AppendLine($"        await Publish_{e.MethodSafeName}(__evt, cancellationToken, fromTransport: true, messageHeaders: headers).ConfigureAwait(false);");
                cb.AppendLine("        return;");
                cb.AppendLine("    }");
            }
            cb.CloseBrace();
        }
        cb.AppendLine("// Unknown event type — silently ignore so transport listeners survive type drift between deployments.");
        cb.CloseBrace();
    }

    // ─── Per-message inner dispatchers ──────────────────────────────────────────────────────────

    private static void EmitSendInner(CodeBuilder cb, RequestDispatch r, HandlerCatalog catalog)
    {
        cb.AppendLine($"private async global::System.Threading.Tasks.ValueTask<{r.ResponseFullName}> Send_{r.MethodSafeName}({r.RequestFullName} request, global::System.Threading.CancellationToken cancellationToken)");
        cb.OpenBrace();
        EmitActivityStart(cb, catalog, kind: "request", spanSuffix: r.MethodSafeName, messageType: r.RequestFullName,
            extraTags: [($"\"mosaic.handler.type\"", $"\"{Strip(r.HandlerFullName)}\"")]);
        cb.AppendLine($"var __ctx = new global::Mosaic.Runtime.CompositionContext(_services, this, {EventPublishModeLiteral(catalog)});");
        if (catalog.EmitTelemetry)
        {
            cb.AppendLine("__act?.SetTag(\"mosaic.correlation_id\", __ctx.CorrelationId);");
        }
        cb.AppendLine($"var __handler = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Mosaic.IRequestHandler<{r.RequestFullName}, {r.ResponseFullName}>>(_services);");

        if (r.BehaviorClosedFullNames.Count == 0)
        {
            cb.AppendLine("var __result = await __handler.Handle(request, __ctx, cancellationToken).ConfigureAwait(false);");
        }
        else
        {
            // Resolve behaviors outermost-first as listed; build the chain inside-out so
            // outermost wraps innermost, with the terminal handler at the core.
            for (int i = 0; i < r.BehaviorClosedFullNames.Count; i++)
            {
                cb.AppendLine($"var __b{i} = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<{r.BehaviorClosedFullNames[i]}>(_services);");
            }

            cb.AppendLine($"global::Mosaic.RequestHandlerDelegate<{r.ResponseFullName}> __next0 = () => __handler.Handle(request, __ctx, cancellationToken);");
            for (int i = r.BehaviorClosedFullNames.Count - 1; i >= 0; i--)
            {
                var prev = r.BehaviorClosedFullNames.Count - 1 - i; // 0-based level number from inside
                var next = prev + 1;
                cb.AppendLine($"global::Mosaic.RequestHandlerDelegate<{r.ResponseFullName}> __next{next} = () => __b{i}.Handle(request, __next{prev}, __ctx, cancellationToken);");
            }
            cb.AppendLine($"var __result = await __next{r.BehaviorClosedFullNames.Count}().ConfigureAwait(false);");
        }

        cb.AppendLine("await __ctx.FlushBufferedEventsAsync(cancellationToken).ConfigureAwait(false);");
        cb.AppendLine("return __result;");
        cb.CloseBrace();
    }

    private static void EmitComposeInner(CodeBuilder cb, ComposableDispatch c, HandlerCatalog catalog)
    {
        cb.AppendLine($"private async global::System.Threading.Tasks.ValueTask<{c.ViewModelFullName}> Compose_{c.MethodSafeName}({c.RequestFullName} request, {c.ViewModelFullName} viewModel, global::System.Threading.CancellationToken cancellationToken)");
        cb.OpenBrace();
        EmitActivityStart(cb, catalog, kind: "composable", spanSuffix: c.MethodSafeName, messageType: c.RequestFullName,
            extraTags: [($"\"mosaic.composer.count\"", c.ComposerFullNames.Count.ToString(System.Globalization.CultureInfo.InvariantCulture))]);
        cb.AppendLine($"var __ctx = new global::Mosaic.Runtime.CompositionContext(_services, this, {EventPublishModeLiteral(catalog)});");
        if (catalog.EmitTelemetry)
        {
            cb.AppendLine("__act?.SetTag(\"mosaic.correlation_id\", __ctx.CorrelationId);");
        }

        for (int i = 0; i < c.ComposerFullNames.Count; i++)
        {
            cb.AppendLine($"var __c{i} = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<{c.ComposerFullNames[i]}>(_services);");
        }

        // Terminal — composer fan-out wrapped as a ComposeHandlerDelegate so behaviors can chain over it.
        cb.AppendLine($"global::Mosaic.ComposeHandlerDelegate __terminal = async () =>");
        cb.OpenBrace();
        if (c.ComposerFullNames.Count == 1)
        {
            cb.AppendLine("await __c0.Compose(request, viewModel, __ctx, cancellationToken).ConfigureAwait(false);");
        }
        else if (c.ComposerFullNames.Count > 1)
        {
            for (int i = 0; i < c.ComposerFullNames.Count; i++)
            {
                cb.AppendLine($"var __t{i} = __c{i}.Compose(request, viewModel, __ctx, cancellationToken).AsTask();");
            }
            cb.Append("await global::System.Threading.Tasks.Task.WhenAll(");
            for (int i = 0; i < c.ComposerFullNames.Count; i++)
            {
                if (i > 0) cb.Append(", ");
                cb.Append($"__t{i}");
            }
            cb.AppendLine(").ConfigureAwait(false);");
        }
        cb.CloseBrace(suffix: ";");

        // Behavior chain (compose-behaviors), outermost-listed last so they wrap the terminal first.
        if (c.BehaviorClosedFullNames.Count == 0)
        {
            cb.AppendLine("await __terminal().ConfigureAwait(false);");
        }
        else
        {
            for (int i = 0; i < c.BehaviorClosedFullNames.Count; i++)
            {
                cb.AppendLine($"var __cb{i} = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<{c.BehaviorClosedFullNames[i]}>(_services);");
            }

            cb.AppendLine("global::Mosaic.ComposeHandlerDelegate __next0 = __terminal;");
            for (int i = c.BehaviorClosedFullNames.Count - 1; i >= 0; i--)
            {
                var prev = c.BehaviorClosedFullNames.Count - 1 - i;
                var next = prev + 1;
                cb.AppendLine($"global::Mosaic.ComposeHandlerDelegate __next{next} = () => __cb{i}.Handle(request, viewModel, __next{prev}, __ctx, cancellationToken);");
            }
            cb.AppendLine($"await __next{c.BehaviorClosedFullNames.Count}().ConfigureAwait(false);");
        }

        cb.AppendLine("await __ctx.FlushBufferedEventsAsync(cancellationToken).ConfigureAwait(false);");
        cb.AppendLine("return viewModel;");
        cb.CloseBrace();
    }

    private static void EmitPublishInner(CodeBuilder cb, EventDispatch e, HandlerCatalog catalog)
    {
        cb.AppendLine($"private async global::System.Threading.Tasks.ValueTask Publish_{e.MethodSafeName}({e.EventFullName} notification, global::System.Threading.CancellationToken cancellationToken, bool fromTransport, global::Mosaic.MessageHeaders? messageHeaders = null)");
        cb.OpenBrace();
        EmitActivityStart(cb, catalog, kind: "event", spanSuffix: e.MethodSafeName, messageType: e.EventFullName,
            extraTags: [($"\"mosaic.handler.count\"", e.HandlerFullNames.Count.ToString(System.Globalization.CultureInfo.InvariantCulture))]);

        var n = e.HandlerFullNames.Count;

        // Headers for THIS message — fall back to a fresh chain root if the caller didn't supply
        // one (top-level engine.Publish from outside any handler context). Same headers feed both
        // the per-handler CompositionContexts AND the outbound transport publish, so handlers see
        // the same MessageId / Correlation / Causation that's stamped on the wire.
        cb.AppendLine("var __headers = messageHeaders ?? global::Mosaic.MessageHeaders.NewRoot();");

        // Behaviors run with a context resolved at the engine's scope (the call-site scope).
        // Per-handler sub-contexts are created inside the terminal so each handler still gets
        // its own DI scope.
        cb.AppendLine($"var __ctx = new global::Mosaic.Runtime.CompositionContext(_services, this, {EventPublishModeLiteral(catalog)}, __headers);");
        if (catalog.EmitTelemetry)
        {
            cb.AppendLine("__act?.SetTag(\"mosaic.correlation_id\", __ctx.CorrelationId);");
        }

        // Terminal: per-handler DI sub-scopes + fan-out + cross-process transport. Wrapped as a
        // PublishHandlerDelegate so publish-behaviors can chain over it.
        cb.AppendLine($"global::Mosaic.PublishHandlerDelegate __terminal = async () =>");
        cb.OpenBrace();
        // Each handler runs in its own DI sub-scope so parallel handlers that transit chains
        // touching the same scoped service (typically a DbContext) don't share state — EF Core
        // throws "second operation on this context instance" otherwise.
        for (int i = 0; i < n; i++)
        {
            cb.AppendLine($"var __scope{i} = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.CreateAsyncScope(_services);");
        }
        cb.AppendLine("try");
        cb.OpenBrace();

        for (int i = 0; i < n; i++)
        {
            cb.AppendLine($"var __engine{i} = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Mosaic.ICompositionEngine>(__scope{i}.ServiceProvider);");
            cb.AppendLine($"var __ctx{i} = new global::Mosaic.Runtime.CompositionContext(__scope{i}.ServiceProvider, __engine{i}, {EventPublishModeLiteral(catalog)}, __headers);");
            cb.AppendLine($"var __h{i} = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<{e.HandlerFullNames[i]}>(__scope{i}.ServiceProvider);");
        }

        if (n == 1)
        {
            cb.AppendLine("await global::Mosaic.Runtime.CompositionContext.HandleAndFlushAsync(__h0.Handle(notification, __ctx0, cancellationToken).AsTask(), __ctx0, cancellationToken).ConfigureAwait(false);");
        }
        else if (n > 1)
        {
            for (int i = 0; i < n; i++)
            {
                cb.AppendLine($"var __t{i} = global::Mosaic.Runtime.CompositionContext.HandleAndFlushAsync(__h{i}.Handle(notification, __ctx{i}, cancellationToken).AsTask(), __ctx{i}, cancellationToken);");
            }
            cb.Append("await global::System.Threading.Tasks.Task.WhenAll(");
            for (int i = 0; i < n; i++)
            {
                if (i > 0) cb.Append(", ");
                cb.Append($"__t{i}");
            }
            cb.AppendLine(").ConfigureAwait(false);");
        }

        cb.CloseBrace();   // try
        cb.AppendLine("finally");
        cb.OpenBrace();
        for (int i = 0; i < n; i++)
        {
            cb.AppendLine($"await __scope{i}.DisposeAsync().ConfigureAwait(false);");
        }
        cb.CloseBrace();   // finally

        // Cross-process publish (skipped when this dispatch was triggered by a transport-delivered
        // event — prevents loops). Default IEventTransport is InProcessOnlyTransport (no-op); a
        // real transport package replaces it via TryAdd-friendly registration.
        var stripped = Strip(e.EventFullName);
        cb.AppendLine("if (!fromTransport)");
        cb.OpenBrace();
        // Serialise via the registry-resolved IMosaicSerializer<TEvent> rather than hard-coding
        // System.Text.Json — lets consumers register a different impl (MemoryPack, MessagePack,
        // hand-rolled) without us re-emitting the dispatcher.
        cb.AppendLine($"var __serializer = _serializerRegistry.GetSerializer<{e.EventFullName}>();");
        cb.AppendLine("using var __writer = global::Mosaic.Runtime.MosaicBufferWriter.Rent();");
        cb.AppendLine("__serializer.Serialize(__writer, notification);");
        cb.AppendLine($"await _transport.PublishAsync(\"{stripped}\", __headers, new global::System.Buffers.ReadOnlySequence<byte>(__writer.WrittenMemory), cancellationToken).ConfigureAwait(false);");
        // Audit AFTER the publish succeeds — failed publishes shouldn't pollute the chain log.
        // Default registration is the no-op store, so this is free unless the consumer opted in.
        cb.AppendLine($"await _auditStore.WriteAsync(new global::Mosaic.MessageAuditEntry(global::System.DateTime.UtcNow, \"{stripped}\", global::Mosaic.MessageAuditDirection.Sent, __headers), cancellationToken).ConfigureAwait(false);");
        cb.CloseBrace();
        cb.CloseBrace(suffix: ";");   // __terminal lambda

        // Behavior chain (publish-behaviors), outermost-listed last so they wrap the terminal first.
        if (e.BehaviorClosedFullNames.Count == 0)
        {
            cb.AppendLine("await __terminal().ConfigureAwait(false);");
        }
        else
        {
            for (int i = 0; i < e.BehaviorClosedFullNames.Count; i++)
            {
                cb.AppendLine($"var __pb{i} = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<{e.BehaviorClosedFullNames[i]}>(_services);");
            }

            cb.AppendLine("global::Mosaic.PublishHandlerDelegate __next0 = __terminal;");
            for (int i = e.BehaviorClosedFullNames.Count - 1; i >= 0; i--)
            {
                var prev = e.BehaviorClosedFullNames.Count - 1 - i;
                var next = prev + 1;
                cb.AppendLine($"global::Mosaic.PublishHandlerDelegate __next{next} = () => __pb{i}.Handle(notification, __next{prev}, __ctx, cancellationToken);");
            }
            cb.AppendLine($"await __next{e.BehaviorClosedFullNames.Count}().ConfigureAwait(false);");
        }

        cb.CloseBrace();   // method
    }

    // ─── Helpers ────────────────────────────────────────────────────────────────────────────────

    /// <summary>
    /// Emits <c>using var __act = MosaicActivitySource.Instance.StartActivity("Mosaic.{kind} {name}")</c>
    /// followed by tag-set calls. No-op if telemetry is disabled in the catalog. Tags use the
    /// well-known keys defined on <c>MosaicActivitySource.Tags</c>.
    /// </summary>
    private static void EmitActivityStart(
        CodeBuilder cb,
        HandlerCatalog catalog,
        string kind,
        string spanSuffix,
        string messageType,
        IReadOnlyList<(string KeyExpr, string ValueExpr)> extraTags)
    {
        if (!catalog.EmitTelemetry) return;

        // Span name: "Mosaic.<Verb> <SimpleName>" — readable in trace UIs without being verbose.
        var verb = kind switch { "request" => "Send", "composable" => "Compose", "event" => "Publish", _ => "Dispatch" };
        cb.AppendLine($"using var __act = global::Mosaic.Runtime.MosaicActivitySource.Instance.StartActivity(\"Mosaic.{verb} {spanSuffix}\");");
        cb.AppendLine($"__act?.SetTag(\"mosaic.message.kind\", \"{kind}\");");
        cb.AppendLine($"__act?.SetTag(\"mosaic.message.type\", \"{Strip(messageType)}\");");
        foreach (var (keyExpr, valueExpr) in extraTags)
        {
            cb.AppendLine($"__act?.SetTag({keyExpr}, {valueExpr});");
        }
    }

    private static string EventPublishModeLiteral(HandlerCatalog catalog)
        => $"global::Mosaic.EventPublishMode.{catalog.EventPublishMode}";

    /// <summary>Removes the leading <c>global::</c> from a fully-qualified type name for cleaner tag values.</summary>
    private static string Strip(string fullyQualified)
        => fullyQualified.StartsWith("global::", StringComparison.Ordinal) ? fullyQualified.Substring(8) : fullyQualified;
}
