using Mosaic.SourceGenerator.Analysis;

namespace Mosaic.SourceGenerator.Emit;

internal static class RegistrationEmitter
{
    public static string Emit(HandlerCatalog catalog)
    {
        var cb = new CodeBuilder();

        cb.AppendLine("// <auto-generated />");
        cb.AppendLine("// Generated by Mosaic.SourceGenerator. Do not edit.");
        cb.AppendLine("#nullable enable");
        cb.AppendLine();
        cb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        cb.AppendLine("using Microsoft.Extensions.DependencyInjection.Extensions;");
        cb.AppendLine("using Mosaic;");
        cb.AppendLine();

        // Place the extension method in the conventional Microsoft.Extensions.DependencyInjection
        // namespace so consumers don't need an extra `using` directive.
        cb.AppendLine("namespace Microsoft.Extensions.DependencyInjection;");
        cb.AppendLine();

        cb.AppendLine("/// <summary>Source-generated DI registration for the Mosaic composition engine and all discovered handlers.</summary>");
        cb.AppendLine("public static class MosaicServiceCollectionExtensions");
        cb.OpenBrace();

        cb.AppendLine("/// <summary>Registers the Mosaic composition engine, all request handlers, composers, event handlers, and pipeline behaviors discovered in the consumer's compilation. Returns an IMosaicBuilder so transports + other Mosaic-specific config can chain off.</summary>");
        cb.AppendLine("public static global::Mosaic.IMosaicBuilder AddMosaic(this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        cb.OpenBrace();

        cb.AppendLine($"global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddScoped<global::Mosaic.ICompositionEngine, global::{catalog.GeneratedNamespace}.GeneratedCompositionEngine>(services);");
        // Same instance also serves as IInboundEventDispatcher (used by transport implementations).
        cb.AppendLine($"global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddScoped<global::Mosaic.IInboundEventDispatcher>(services, static sp => (global::{catalog.GeneratedNamespace}.GeneratedCompositionEngine)global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Mosaic.ICompositionEngine>(sp));");
        // Default in-process-only transport — replaced by TryAdd-friendly registration in real transport packages.
        cb.AppendLine($"global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddSingleton<global::Mosaic.IEventTransport, global::Mosaic.Runtime.InProcessOnlyTransport>(services);");
        // Resilience defaults: in-memory dead-letter store + default options. Transport packages
        // can replace IDeadLetterStore (e.g. with a Postgres-backed one) and reconfigure the options.
        cb.AppendLine($"global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddSingleton<global::Mosaic.IDeadLetterStore, global::Mosaic.Runtime.InMemoryDeadLetterStore>(services);");
        cb.AppendLine($"global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddSingleton<global::Mosaic.Runtime.MosaicResilienceOptions>(services);");
        // Default recoverability policy: retry up to MaxAttempts with backoff, then DLQ.
        // Replace via builder.UseRecoverability<TPolicy>() / UseRecoverability(decideFn) for
        // per-exception rules.
        cb.AppendLine($"global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddSingleton<global::Mosaic.IRecoverabilityPolicy, global::Mosaic.Runtime.DefaultRecoverabilityPolicy>(services);");
        // Default critical-error handler: log at Critical and continue. Real deployments wire
        // builder.UseCriticalErrorHandler<TYours>() for paging / Slack / endpoint shutdown.
        cb.AppendLine($"global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddSingleton<global::Mosaic.ICriticalErrorHandler, global::Mosaic.Runtime.LoggingCriticalErrorHandler>(services);");
        // Default serializer registry — System.Text.Json. Replace with MemoryPack/MessagePack/etc
        // by registering your own IMosaicSerializerRegistry singleton BEFORE AddMosaic() runs (the
        // TryAdd here only registers the default if no other impl is already in the collection).
        cb.AppendLine($"global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddSingleton<global::Mosaic.IMosaicSerializerRegistry, global::Mosaic.Runtime.DefaultMosaicSerializerRegistry>(services);");
        // Default audit store: discards everything. Opt-in real auditing via builder.UseAuditing<TStore>().
        cb.AppendLine($"global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddSingleton<global::Mosaic.IMessageAuditStore>(services, global::Mosaic.Runtime.NoOpMessageAuditStore.Instance);");
        cb.AppendLine();

        foreach (var reg in catalog.Registrations)
        {
            EmitRegistration(cb, reg);
        }

        // Auto-register the EF Core saga state store for each saga whose primary constructor
        // accepts a DbContext — preserves the convention from before the storage abstraction was
        // introduced. Only runs when Mosaic.Sagas.EFCore is referenced; sagas without a DbContext
        // ctor parameter need a manual ISagaStateStore<TData> registration (custom backend).
        if (catalog.EFCoreSagaStateStoreAvailable)
        {
            foreach (var saga in catalog.Sagas)
            {
                if (string.IsNullOrEmpty(saga.DbContextFullName)) continue;
                cb.AppendLine($"global::Mosaic.Sagas.EFCore.SagaEFCoreServiceCollectionExtensions.AddEFCoreSagaState<{saga.DbContextFullName}, {saga.DataFullName}>(services);");
            }
        }

        cb.AppendLine();
        cb.AppendLine("return new global::Mosaic.MosaicBuilder(services);");
        cb.CloseBrace();

        cb.CloseBrace();

        return cb.ToString();
    }

    private static void EmitRegistration(CodeBuilder cb, HandlerRegistration reg)
    {
        // Registrations come in two flavors:
        //  - service != impl  → Add<TService, TImpl>() with explicit interface
        //  - service == impl  → Add<TConcrete>() — composer/event-handler discovered by class
        var serviceIsConcrete = string.Equals(reg.ServiceTypeFullName, reg.ImplementationFullName, StringComparison.Ordinal);
        var addMethod = reg.Lifetime switch
        {
            "Singleton" => "AddSingleton",
            "Transient" => "AddTransient",
            _ => "AddScoped",
        };

        if (serviceIsConcrete)
        {
            cb.AppendLine($"global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.{addMethod}<{reg.ImplementationFullName}>(services);");
        }
        else
        {
            cb.AppendLine($"global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.{addMethod}<{reg.ServiceTypeFullName}, {reg.ImplementationFullName}>(services);");
        }
    }
}
