using Mosaic.SourceGenerator.Analysis;

namespace Mosaic.SourceGenerator.Emit;

/// <summary>
/// Emits per-message <c>IEventHandler&lt;TMessage&gt;</c> wrapper classes for each
/// <see cref="SagaDispatch"/>: each wrapper resolves the saga + an <see cref="ISagaStateStore{TData}"/>
/// from DI, runs the finder lookup (convention or <c>CorrelateBy</c> partial), seeds a new state
/// row for starter messages, sets the saga's <c>Data</c> property, invokes the user's
/// <c>Handle</c> method, and commits via the store. <see cref="DuringAttribute"/> guards become
/// early-return state checks at the top of the wrapped call.
/// <para>
/// The wrapper is storage-agnostic: <see cref="ISagaStateStore{TData}"/> is the abstraction.
/// Mosaic.Sagas.EFCore provides an EF Core adapter (auto-registered when the saga's primary
/// constructor accepts a DbContext); other backends are user-registered.
/// </para>
/// </summary>
internal static class SagaEmitter
{
    public static string Emit(HandlerCatalog catalog)
    {
        var cb = new CodeBuilder();

        cb.AppendLine("// <auto-generated />");
        cb.AppendLine("// Generated by Mosaic.SourceGenerator (saga wrappers). Do not edit.");
        cb.AppendLine("#nullable enable");
        cb.AppendLine();
        cb.AppendLine("using System;");
        cb.AppendLine("using System.Threading;");
        cb.AppendLine("using System.Threading.Tasks;");
        cb.AppendLine();
        cb.AppendLine($"namespace {catalog.GeneratedNamespace};");
        cb.AppendLine();

        if (catalog.Sagas.Count == 0)
        {
            cb.AppendLine("// (No sagas discovered in this compilation.)");
            return cb.ToString();
        }

        foreach (var saga in catalog.Sagas)
        {
            foreach (var msg in saga.Messages)
            {
                EmitWrapper(cb, saga, msg);
                cb.AppendLine();
            }
        }

        return cb.ToString();
    }

    private static void EmitWrapper(CodeBuilder cb, SagaDispatch saga, SagaMessage msg)
    {
        var className = $"{saga.SagaSimpleName}_{msg.MessageSimpleName}_Handler";
        var corrIsId = string.Equals(saga.CorrelationPropertyName, "Id", System.StringComparison.Ordinal);
        var storeFullName = $"global::Mosaic.Sagas.ISagaStateStore<{saga.DataFullName}>";

        cb.AppendLine($"/// <summary>Generated saga wrapper: dispatches {msg.MessageFullName} to {saga.SagaFullName}.</summary>");
        cb.AppendLine($"internal sealed class {className} : global::Mosaic.IEventHandler<{msg.MessageFullName}>");
        cb.OpenBrace();

        cb.AppendLine($"private readonly {saga.SagaFullName} _saga;");
        cb.AppendLine($"private readonly {storeFullName} _store;");
        cb.AppendLine();
        cb.AppendLine($"public {className}({saga.SagaFullName} saga, {storeFullName} store)");
        cb.OpenBrace();
        cb.AppendLine("_saga = saga;");
        cb.AppendLine("_store = store;");
        cb.CloseBrace();
        cb.AppendLine();

        cb.AppendLine($"public async global::System.Threading.Tasks.ValueTask Handle({msg.MessageFullName} message, global::Mosaic.ICompositionContext context, global::System.Threading.CancellationToken cancellationToken)");
        cb.OpenBrace();

        // 1. Resolve correlation value
        if (msg.HasCorrelateByPartial)
        {
            cb.AppendLine($"var __corr = {saga.SagaFullName}.CorrelateBy(message);");
        }
        else
        {
            cb.AppendLine($"var __corr = message.{msg.CorrelationAccessorOnMessage};");
        }

        // 2. Lookup existing state via the store abstraction
        cb.AppendLine($"var __existing = await _store.FindAsync(d => d.{saga.CorrelationPropertyName} == __corr, cancellationToken).ConfigureAwait(false);");
        cb.AppendLine();

        cb.AppendLine($"{saga.DataFullName} __data;");
        cb.AppendLine("if (__existing is null)");
        cb.OpenBrace();
        if (msg.IsStarter)
        {
            // Create fresh state row
            cb.AppendLine($"__data = new {saga.DataFullName}");
            cb.OpenBrace();
            if (corrIsId)
            {
                cb.AppendLine("Id = __corr,");
            }
            else
            {
                cb.AppendLine("Id = global::System.Guid.NewGuid(),");
                cb.AppendLine($"{saga.CorrelationPropertyName} = __corr,");
            }
            cb.CloseBrace(suffix: ";");
            cb.AppendLine("_store.Add(__data);");
        }
        else
        {
            // No state, no starter — route to saga-not-found policy
            cb.AppendLine("await context.HandleSagaNotFoundAsync(message, cancellationToken).ConfigureAwait(false);");
            cb.AppendLine("return;");
        }
        cb.CloseBrace();
        cb.AppendLine("else");
        cb.OpenBrace();
        cb.AppendLine("__data = __existing;");
        cb.CloseBrace();
        cb.AppendLine();

        // 3. Skip if completed
        cb.AppendLine("if (__data.IsCompleted) return;");
        cb.AppendLine();

        // 4. [During] state guard
        if (msg.DuringStates.Count > 0)
        {
            var conds = string.Join(" && ", msg.DuringStates.Select(s => $"__data.CurrentState != \"{s}\""));
            cb.AppendLine($"if ({conds}) return;");
            cb.AppendLine();
        }

        // 5. Set Data + invoke user's Handle
        cb.AppendLine("_saga.Data = __data;");
        cb.AppendLine("await _saga.Handle(message, context, cancellationToken).ConfigureAwait(false);");
        cb.AppendLine();

        // 6. Lifecycle: delete + cancel pending timeouts on Complete()
        cb.AppendLine("if (__data.IsCompleted)");
        cb.OpenBrace();
        cb.AppendLine("_store.Remove(__data);");
        // Cancel every still-pending timeout this saga had scheduled. Resolve the store from the
        // current scope; a no-op if scheduling isn't wired into the host (just leaves any rows in
        // place — they'd route to IHandleSagaNotFound when they fire).
        cb.AppendLine("var __schedStore = (global::Mosaic.IScheduledMessageStore?)context.Services.GetService(typeof(global::Mosaic.IScheduledMessageStore));");
        cb.AppendLine("if (__schedStore is not null)");
        cb.OpenBrace();
        cb.AppendLine("await __schedStore.CancelByPrefixAsync(global::Mosaic.Sagas.SagaTimeoutKey.PrefixFor(__data.Id), cancellationToken).ConfigureAwait(false);");
        cb.CloseBrace();
        cb.CloseBrace();
        cb.AppendLine();

        // 7. Save (state changes + outbox/inbox rows + completion delete all in one tx for
        //    backends like EF Core; in-memory backends apply immediately on Add/Remove).
        cb.AppendLine("await _store.SaveChangesAsync(cancellationToken).ConfigureAwait(false);");

        cb.CloseBrace();   // method
        cb.CloseBrace();   // class
    }
}
