//HintName: Mosaic.GeneratedCompositionEngine.g.cs
// <auto-generated />
// Generated by Mosaic.SourceGenerator. Do not edit.
#nullable enable

using System;
using System.Runtime.CompilerServices;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using Mosaic;
using Mosaic.Runtime;

namespace TestAssembly.Generated.Mosaic;

/// <summary>Source-generated implementation of <see cref="global::Mosaic.ICompositionEngine"/>.</summary>
internal sealed class GeneratedCompositionEngine : global::Mosaic.ICompositionEngine, global::Mosaic.IInboundEventDispatcher
{
    private readonly global::System.IServiceProvider _services;
    private readonly global::Mosaic.IEventTransport _transport;
    private readonly global::Mosaic.IMosaicSerializerRegistry _serializerRegistry;
    private readonly global::Mosaic.IMessageAuditStore _auditStore;

    public GeneratedCompositionEngine(global::System.IServiceProvider services, global::Mosaic.IEventTransport transport, global::Mosaic.IMosaicSerializerRegistry serializerRegistry, global::Mosaic.IMessageAuditStore auditStore)
    {
        _services = services;
        _transport = transport;
        _serializerRegistry = serializerRegistry;
        _auditStore = auditStore;
    }

    public global::System.Threading.Tasks.ValueTask<TResponse> Send<TResponse>(global::Mosaic.IRequest<TResponse> request, global::System.Threading.CancellationToken cancellationToken = default)
    {
        throw new global::Mosaic.SendNoHandlerException(request.GetType());
    }

    public global::System.Threading.Tasks.ValueTask<TViewModel> Compose<TViewModel>(global::Mosaic.IComposable<TViewModel> request, global::System.Threading.CancellationToken cancellationToken = default)
        where TViewModel : new()
    {
        switch (request)
        {
            case global::Sample.GetOrder __r:
                {
                    var __task = Compose_GetOrder(__r, new global::Sample.OrderVm(), cancellationToken);
                    return global::System.Runtime.CompilerServices.Unsafe.As<global::System.Threading.Tasks.ValueTask<global::Sample.OrderVm>, global::System.Threading.Tasks.ValueTask<TViewModel>>(ref __task);
                }
        }
        throw new global::Mosaic.ComposeNoHandlerException(request.GetType(), typeof(TViewModel));
    }

    public global::System.Threading.Tasks.ValueTask Compose<TViewModel>(global::Mosaic.IComposable<TViewModel> request, TViewModel existing, global::System.Threading.CancellationToken cancellationToken = default)
    {
        switch (request)
        {
            case global::Sample.GetOrder __r:
                return new global::System.Threading.Tasks.ValueTask(Compose_GetOrder(__r, (global::Sample.OrderVm)(object)existing!, cancellationToken).AsTask());
        }
        throw new global::Mosaic.ComposeNoHandlerException(request.GetType(), typeof(TViewModel));
    }

    public global::System.Threading.Tasks.ValueTask Publish<TEvent>(TEvent notification, global::System.Threading.CancellationToken cancellationToken = default, global::Mosaic.MessageHeaders? messageHeaders = null)
        where TEvent : global::Mosaic.IEvent
    {
        // No handlers registered for this event type — silent no-op.
        return default;
    }

    public async global::System.Threading.Tasks.Task DispatchInboundAsync(string typeFullName, global::Mosaic.MessageHeaders headers, global::System.Buffers.ReadOnlySequence<byte> payload, global::System.Threading.CancellationToken cancellationToken = default)
    {
        // Unknown event type — silently ignore so transport listeners survive type drift between deployments.
    }

    private async global::System.Threading.Tasks.ValueTask<global::Sample.OrderVm> Compose_GetOrder(global::Sample.GetOrder request, global::Sample.OrderVm viewModel, global::System.Threading.CancellationToken cancellationToken)
    {
        using var __act = global::Mosaic.Runtime.MosaicActivitySource.Instance.StartActivity("Mosaic.Compose GetOrder");
        __act?.SetTag("mosaic.message.kind", "composable");
        __act?.SetTag("mosaic.message.type", "Sample.GetOrder");
        __act?.SetTag("mosaic.composer.count", 2);
        var __ctx = new global::Mosaic.Runtime.CompositionContext(_services, this, global::Mosaic.EventPublishMode.Buffered);
        __act?.SetTag("mosaic.correlation_id", __ctx.CorrelationId);
        var __c0 = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Sample.TotalsComposer>(_services);
        var __c1 = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Sample.IdComposer>(_services);
        global::Mosaic.ComposeHandlerDelegate __terminal = async () =>
        {
            var __t0 = __c0.Compose(request, viewModel, __ctx, cancellationToken).AsTask();
            var __t1 = __c1.Compose(request, viewModel, __ctx, cancellationToken).AsTask();
            await global::System.Threading.Tasks.Task.WhenAll(__t0, __t1).ConfigureAwait(false);
        };
        await __terminal().ConfigureAwait(false);
        await __ctx.FlushBufferedEventsAsync(cancellationToken).ConfigureAwait(false);
        return viewModel;
    }

}
