//HintName: Mosaic.AddMosaic.g.cs
// <auto-generated />
// Generated by Mosaic.SourceGenerator. Do not edit.
#nullable enable

using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;
using Mosaic;

namespace Microsoft.Extensions.DependencyInjection;

/// <summary>Source-generated DI registration for the Mosaic composition engine and all discovered handlers.</summary>
public static class MosaicServiceCollectionExtensions
{
    /// <summary>Registers the Mosaic composition engine, all request handlers, composers, event handlers, and pipeline behaviors discovered in the consumer's compilation. Returns an IMosaicBuilder so transports + other Mosaic-specific config can chain off.</summary>
    public static global::Mosaic.IMosaicBuilder AddMosaic(this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)
    {
        global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddScoped<global::Mosaic.ICompositionEngine, global::MyApp.MosaicGen.GeneratedCompositionEngine>(services);
        global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddScoped<global::Mosaic.IInboundEventDispatcher>(services, static sp => (global::MyApp.MosaicGen.GeneratedCompositionEngine)global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Mosaic.ICompositionEngine>(sp));
        global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddSingleton<global::Mosaic.IEventTransport, global::Mosaic.Runtime.InProcessOnlyTransport>(services);
        global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddSingleton<global::Mosaic.IDeadLetterStore, global::Mosaic.Runtime.InMemoryDeadLetterStore>(services);
        global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddSingleton<global::Mosaic.Runtime.MosaicResilienceOptions>(services);
        global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddSingleton<global::Mosaic.IRecoverabilityPolicy, global::Mosaic.Runtime.DefaultRecoverabilityPolicy>(services);
        global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddSingleton<global::Mosaic.ICriticalErrorHandler, global::Mosaic.Runtime.LoggingCriticalErrorHandler>(services);
        global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddSingleton<global::Mosaic.IMosaicSerializerRegistry, global::Mosaic.Runtime.DefaultMosaicSerializerRegistry>(services);
        global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddSingleton<global::Mosaic.IMessageAuditStore>(services, global::Mosaic.Runtime.NoOpMessageAuditStore.Instance);

        global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddSingleton<global::Mosaic.IRequestHandler<global::Sample.Ping, int>, global::Sample.PingHandler>(services);

        return new global::Mosaic.MosaicBuilder(services);
    }
}
