//HintName: Mosaic.GeneratedCompositionEngine.g.cs
// <auto-generated />
// Generated by Mosaic.SourceGenerator. Do not edit.
#nullable enable

using System;
using System.Runtime.CompilerServices;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using Mosaic;
using Mosaic.Runtime;

namespace TestAssembly.Generated.Mosaic;

/// <summary>Source-generated implementation of <see cref="global::Mosaic.ICompositionEngine"/>.</summary>
internal sealed class GeneratedCompositionEngine : global::Mosaic.ICompositionEngine, global::Mosaic.IInboundEventDispatcher
{
    private readonly global::System.IServiceProvider _services;
    private readonly global::Mosaic.IEventTransport _transport;
    private readonly global::Mosaic.IMosaicSerializerRegistry _serializerRegistry;
    private readonly global::Mosaic.IMessageAuditStore _auditStore;

    public GeneratedCompositionEngine(global::System.IServiceProvider services, global::Mosaic.IEventTransport transport, global::Mosaic.IMosaicSerializerRegistry serializerRegistry, global::Mosaic.IMessageAuditStore auditStore)
    {
        _services = services;
        _transport = transport;
        _serializerRegistry = serializerRegistry;
        _auditStore = auditStore;
    }

    public global::System.Threading.Tasks.ValueTask<TResponse> Send<TResponse>(global::Mosaic.IRequest<TResponse> request, global::System.Threading.CancellationToken cancellationToken = default)
    {
        throw new global::Mosaic.SendNoHandlerException(request.GetType());
    }

    public global::System.Threading.Tasks.ValueTask<TViewModel> Compose<TViewModel>(global::Mosaic.IComposable<TViewModel> request, global::System.Threading.CancellationToken cancellationToken = default)
        where TViewModel : new()
    {
        throw new global::Mosaic.ComposeNoHandlerException(request.GetType(), typeof(TViewModel));
    }

    public global::System.Threading.Tasks.ValueTask Compose<TViewModel>(global::Mosaic.IComposable<TViewModel> request, TViewModel existing, global::System.Threading.CancellationToken cancellationToken = default)
    {
        throw new global::Mosaic.ComposeNoHandlerException(request.GetType(), typeof(TViewModel));
    }

    public global::System.Threading.Tasks.ValueTask Publish<TEvent>(TEvent notification, global::System.Threading.CancellationToken cancellationToken = default, global::Mosaic.MessageHeaders? messageHeaders = null)
        where TEvent : global::Mosaic.IEvent
    {
        switch (notification)
        {
            case global::Sample.OrderPlaced __e:
                return Publish_OrderPlaced(__e, cancellationToken, fromTransport: false, messageHeaders: messageHeaders);
        }
        // No handlers registered for this event type — silent no-op.
        return default;
    }

    public async global::System.Threading.Tasks.Task DispatchInboundAsync(string typeFullName, global::Mosaic.MessageHeaders headers, global::System.Buffers.ReadOnlySequence<byte> payload, global::System.Threading.CancellationToken cancellationToken = default)
    {
        switch (typeFullName)
        {
            case "Sample.OrderPlaced":
                {
                    var __ser = _serializerRegistry.GetSerializer<global::Sample.OrderPlaced>();
                    var __evt = __ser.Deserialize(payload)
                        ?? throw new global::System.InvalidOperationException("Mosaic: inbound payload for Sample.OrderPlaced deserialised to null.");
                    await Publish_OrderPlaced(__evt, cancellationToken, fromTransport: true, messageHeaders: headers).ConfigureAwait(false);
                    return;
                }
        }
        // Unknown event type — silently ignore so transport listeners survive type drift between deployments.
    }

    private async global::System.Threading.Tasks.ValueTask Publish_OrderPlaced(global::Sample.OrderPlaced notification, global::System.Threading.CancellationToken cancellationToken, bool fromTransport, global::Mosaic.MessageHeaders? messageHeaders = null)
    {
        using var __act = global::Mosaic.Runtime.MosaicActivitySource.Instance.StartActivity("Mosaic.Publish OrderPlaced");
        __act?.SetTag("mosaic.message.kind", "event");
        __act?.SetTag("mosaic.message.type", "Sample.OrderPlaced");
        __act?.SetTag("mosaic.handler.count", 1);
        var __headers = messageHeaders ?? global::Mosaic.MessageHeaders.NewRoot();
        var __ctx = new global::Mosaic.Runtime.CompositionContext(_services, this, global::Mosaic.EventPublishMode.Buffered, __headers);
        __act?.SetTag("mosaic.correlation_id", __ctx.CorrelationId);
        global::Mosaic.PublishHandlerDelegate __terminal = async () =>
        {
            var __scope0 = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.CreateAsyncScope(_services);
            try
            {
                var __engine0 = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Mosaic.ICompositionEngine>(__scope0.ServiceProvider);
                var __ctx0 = new global::Mosaic.Runtime.CompositionContext(__scope0.ServiceProvider, __engine0, global::Mosaic.EventPublishMode.Buffered, __headers);
                var __h0 = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Sample.Auditor>(__scope0.ServiceProvider);
                await global::Mosaic.Runtime.CompositionContext.HandleAndFlushAsync(__h0.Handle(notification, __ctx0, cancellationToken).AsTask(), __ctx0, cancellationToken).ConfigureAwait(false);
            }
            finally
            {
                await __scope0.DisposeAsync().ConfigureAwait(false);
            }
            if (!fromTransport)
            {
                var __serializer = _serializerRegistry.GetSerializer<global::Sample.OrderPlaced>();
                using var __writer = global::Mosaic.Runtime.MosaicBufferWriter.Rent();
                __serializer.Serialize(__writer, notification);
                await _transport.PublishAsync("Sample.OrderPlaced", __headers, new global::System.Buffers.ReadOnlySequence<byte>(__writer.WrittenMemory), cancellationToken).ConfigureAwait(false);
                await _auditStore.WriteAsync(new global::Mosaic.MessageAuditEntry(global::System.DateTime.UtcNow, "Sample.OrderPlaced", global::Mosaic.MessageAuditDirection.Sent, __headers), cancellationToken).ConfigureAwait(false);
            }
        };
        var __pb0 = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Sample.PublishLoggingBehavior<global::Sample.OrderPlaced>>(_services);
        var __pb1 = global::Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService<global::Sample.PublishMetricsBehavior<global::Sample.OrderPlaced>>(_services);
        global::Mosaic.PublishHandlerDelegate __next0 = __terminal;
        global::Mosaic.PublishHandlerDelegate __next1 = () => __pb1.Handle(notification, __next0, __ctx, cancellationToken);
        global::Mosaic.PublishHandlerDelegate __next2 = () => __pb0.Handle(notification, __next1, __ctx, cancellationToken);
        await __next2().ConfigureAwait(false);
    }

}
