//HintName: Mosaic.GeneratedSagas.g.cs
// <auto-generated />
// Generated by Mosaic.SourceGenerator (saga wrappers). Do not edit.
#nullable enable

using System;
using System.Threading;
using System.Threading.Tasks;

namespace TestAssembly.Generated.Mosaic;

// (No sagas discovered in this compilation.)
