//HintName: Mosaic.GeneratedSagas.g.cs
// <auto-generated />
// Generated by Mosaic.SourceGenerator (saga wrappers). Do not edit.
#nullable enable

using System;
using System.Threading;
using System.Threading.Tasks;

namespace TestAssembly.Generated.Mosaic;

/// <summary>Generated saga wrapper: dispatches global::Sample.LegacyOrderEvent to global::Sample.OrderProcessSaga.</summary>
internal sealed class OrderProcessSaga_LegacyOrderEvent_Handler : global::Mosaic.IEventHandler<global::Sample.LegacyOrderEvent>
{
    private readonly global::Sample.OrderProcessSaga _saga;
    private readonly global::Mosaic.Sagas.ISagaStateStore<global::Sample.OrderProcessData> _store;

    public OrderProcessSaga_LegacyOrderEvent_Handler(global::Sample.OrderProcessSaga saga, global::Mosaic.Sagas.ISagaStateStore<global::Sample.OrderProcessData> store)
    {
        _saga = saga;
        _store = store;
    }

    public async global::System.Threading.Tasks.ValueTask Handle(global::Sample.LegacyOrderEvent message, global::Mosaic.ICompositionContext context, global::System.Threading.CancellationToken cancellationToken)
    {
        var __corr = global::Sample.OrderProcessSaga.CorrelateBy(message);
        var __existing = await _store.FindAsync(d => d.OrderId == __corr, cancellationToken).ConfigureAwait(false);

        global::Sample.OrderProcessData __data;
        if (__existing is null)
        {
            __data = new global::Sample.OrderProcessData
            {
                Id = global::System.Guid.NewGuid(),
                OrderId = __corr,
            };
            _store.Add(__data);
        }
        else
        {
            __data = __existing;
        }

        if (__data.IsCompleted) return;

        _saga.Data = __data;
        await _saga.Handle(message, context, cancellationToken).ConfigureAwait(false);

        if (__data.IsCompleted)
        {
            _store.Remove(__data);
            var __schedStore = (global::Mosaic.IScheduledMessageStore?)context.Services.GetService(typeof(global::Mosaic.IScheduledMessageStore));
            if (__schedStore is not null)
            {
                await __schedStore.CancelByPrefixAsync(global::Mosaic.Sagas.SagaTimeoutKey.PrefixFor(__data.Id), cancellationToken).ConfigureAwait(false);
            }
        }

        await _store.SaveChangesAsync(cancellationToken).ConfigureAwait(false);
    }
}

